### PR TITLE
Added documentation for AbstractApplication.allows_grant_type

### PR DESCRIPTION
**Pull request by clintonb**
This documents the feature added in #448.

### CODE REVIEW

**Comment by clintonb** [comment]
@jleclanche @ddelemeny please review.

**Comment by jleclanche** [comment]
Awesome, can you add a note in the changelog as well?

**Comment by clintonb** [comment]
@jleclanche I can, but for what version? 0.11.0 has been released. Will this be a patch release, or do you intend to add other features that might make this a minor release?

**Comment by jleclanche** [comment]
Put it under the `Unreleased` section.

**Comment by jleclanche** [comment]
@clintonb sorry, when I said add a changelog note, I meant add a note for the `allows_grant_type` method and what it does so people know about it ;)

**Comment by clintonb** [comment]
@jleclanche fixed

**Pull request merged**
