### PR TITLE
Make AccessToken, RefreshToken and Grant models swappable.

### PR DESCRIPTION
**Pull request by menecio**
Make it possible to use custom models for access tokens, refresh tokens and grants.

### CODE REVIEW

**Comment by menecio** [comment]
I started a clean branch after the original got abandoned. https://github.com/evonove/django-oauth-toolkit/pull/347

**Comment by jleclanche** [comment]
At first glance it looks a ton better than before. I think this will be mergeable.

I'll try to find some time to review this. but I'm a bit short on it right now. @clintonb wanna help?

**Comment by menecio** [comment]
@jleclanche I added more test cases, updated docs and cleaned a bit. Please let me know any questions or suggestions you might have.

hi @clintonb

**Comment by jleclanche** [comment]
This is great, but it'll take me a while to get to it and review. It definitely looks landable though, we can get this in for next version.

**Comment by menecio** [comment]
This PR https://github.com/evonove/django-oauth-toolkit/pull/252 is also related to this. I didn't know this was a 3rd attempt to get this feature.

**Comment by menecio** [comment]
@jleclanche I just updated this to with the latest changes merge into master

**Comment by jleclanche** [comment]
@menecio can you rebase it instead of merge? This still has conflicts as-is.

**Comment by menecio** [comment]
@jleclanche Done. Let me know if there is something else. Thank you very much for your time.

**Comment by menecio** [comment]
hey @clintonb I'll ping you to see if you have some time to check this one out. @jleclanche seems to be quite busy. 

Thanks

**Comment by jleclanche** [comment]
Apologies, fell through the crack. Reviewing now.

**Comment by jleclanche** [comment]
@menecio Landed in master with some minor cleanups.

And I just want to thank you for this PR. Not only is it a feature that's been long requested in DOT, but you implemented it cleanly, pushed out well-separated commits, made it really easy to review and just generally kept it high quality. In 10 years of using Github, I can count on one hand the amount of times I've seen this happen for drive-by PRs :)

**Comment by bunchesofdonald** [comment]
Thank you @coveralls! @jleclanche or @clintonb are there any plans to release this to pypi in the near future?

**Comment by clintonb** [comment]
I'm just an interested party, not a maintainer. I have not ability to
release.
-- 
Clinton

**Comment by jleclanche** [comment]
Yeah I can't do releases either.

**Comment by bunchesofdonald** [comment]
Sorry to have bothered you guys! It looks like maybe it's @synasius that can do a release?

**Comment by menecio** [comment]
It would be nice to have some feedback from @synasius about a possible release of this.

**Comment by danadn** [comment]
Any news on this? @synasius would be great to use JWT as access_token (#252 leads here). Thanks.

**Comment by jleclanche** [comment]
The release happened a while ago.

**Comment by danadn** [comment]
Ok, it happens that I looked for documentation for hours about how to setup JWT as the access_token with no luck. 

It isn't clear where do you have to add code to set it, [models.py](https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/models.py) / [settings.py](https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/settings.py) / [mixins.py](https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/views/mixins.py)?

Anyway I understand that documenting this takes extra work. If I find the way myself, I'll try to put it here.

**Pull request closed without merging**
