### PR TITLE
Generic read write scope by resource

### PR DESCRIPTION
**Pull request by drgarcia1986**
I think it's a great feature, the idea in this pull request is working like the [github scopes](https://developer.github.com/v3/oauth/#scopes).

About mock library, I've opened a [pull request in mock repo](https://github.com/testing-cabal/mock/pull/265).

### CODE REVIEW

**Comment by jair-luizalabs** [comment]
:+1: :clap: :tada:

**Comment by jairhenrique** [comment]
:+1: :clap: :tada:

**Comment by renanivo** [comment]
:+1:

**Comment by drgarcia1986** [comment]
@synasius you can review?

**Comment by synasius** [comment]
Hi @drgarcia1986 
PR is great! Thanks for your effort.

Although this is a feature you can easily maintain in your code, we're going to merge because there are other users supporting this PR.

Thanks

**Comment by drgarcia1986** [comment]
:smile:

**Pull request merged**
