### PR TITLE
Add CORS-middleware

### PR DESCRIPTION
**Pull request by cheif**
As discussed in: https://github.com/evonove/django-oauth-toolkit/issues/287

### CODE REVIEW

**Comment by pySilver** [comment]
why not simply use django-cors-headers ?

**Comment by cheif** [comment]
django-cors-headers has no way of determining headers dynamically, this PR aims to solve that. There's more info in the issue I just linked in the PR (forgot that earlier unfortunately)

**Comment by poswald** [comment]
This branch needs updating with develop, a quick mention in the documentation, and an up/down vote on merging it. One question I had was if this replaces django-cors-headers or if it just supplements it's behavior? i.e. would you run both at the same time or not?

It seems others have need for it, it's optional, tested, and as long as it is a sane implementation it seems ok to add.

**Comment by cheif** [comment]
Now it's synced with evonove:master (Didn't find any develop?) and I've added some documentation, I only added to the tutorial (where all django-cors-headers references were removed).
Reg. django-cors-headers, you should be able to ditch it completely. This just uses the redirect uris right away to determine if a request is ok, with django-cors-headers you'll have to add all domains manually.

Does that make sense? (We've been using this approach in prod for several months, since the PR was opened)

**Comment by Dean-Christian-Armada** [comment]
It seems that the changes has not yet been put when using pip,, I also checked my  oauth2_provider.middleware whch was download just last week and it has no "CorsMiddleware" class in it

**Comment by jleclanche** [comment]
Closing PR which at this point is too old to review/merge. If there's interest to revive it please rediscuss in #287.

**Comment by rcmurphy** [comment]
Why was this PR killed? This seems to be novel functionality apart from that offered by django-cors-headers. To allow external clients to hit our API I'm going to have to reimplement this code downstream to replicate the functionality; IMO this is very useful.

**Comment by n2ygk** [comment]
@rcmurphy Like it says, because it's too old to review/merge. Feel free to submit a new PR.

**Comment by rcmurphy** [comment]
Awesome! Will do.

**Pull request closed without merging**
