### PR TITLE
Limit max len of dbindex fields to 191 for mysql utf8mb4 compatibility

### PR DESCRIPTION
**Pull request by JonasSteur**
https://github.com/evonove/django-oauth-toolkit/issues/516

https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-conversion.html

When using mysql with the utf8mb4 character set db index fields can only have a max length of 191 instead of 255.
This pr makes changes in models.py to ensure compatibility. I squashed and adapted migrations while leaving the old ones in place to ensure migrations still keep working in both directions for pre existing installs. New installs will only use the squashed migration.

I did have to add some checks on following settings attributes to be able to run the migrations though:
OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL
OAUTH2_PROVIDER_APPLICATION_MODEL
This probably solves issue #240 as well

### CODE REVIEW

**Comment by orf** [comment]
Should we really limit the length of the fields for all database backends due to a rather ridiculous MySQL specific issue?

**Comment by JonasSteur** [comment]
It's ridiculous but it's either this or fix mysql. For now we had to fork this repo to be able to use it at our company with out current db config.

**Comment by jleclanche** [comment]
Yeah I'm not particularly thrilled about merging that myself to be honest. Especially since this is highly backwards incompatible.

**Comment by jleclanche** [comment]
Actually I glanced over the fact that this is why you squashed the migrations, sorry.

Hmm.. I'm really not sure. Given that all of the models in questions are abstract, have you considered replacing the model fields in question with your own with the updated max length? I know it's a bit silly to ask that of users but maintaining multiple migration paths is a massive pain, and it *is* just mysql...

**Comment by orf** [comment]
You could make the length configurable via a setting, perhaps?

**Comment by jleclanche** [comment]
I'd avoid that. Settings are highly mutable and this would be misleading without doing your own migration.

**Comment by JonasSteur** [comment]
To look at it another way : Will there ever be a case we will need more that 191 characters for these tokens though, no matter what database is in use? And if that need really would arise why not let those users replace the fields ?

This library is just one of the many found with this migration problem after some of our servers got switched to utf8mb4. I'm quite sure we are not the only ones who will run into this. That's why I did this PR instead of just replacing those fields. Usually there's no good reason at all having those fields at max size anyways.

**Comment by jleclanche** [comment]
I agree with you, but I'm reticent on the grounds that complex django migration paths are very hard to maintain in libraries (I'm dealing with having to wipe migrations in dj-stripe currently and it's not simple to push out), and this affects one particular configuration of mysql, a db engine which has a lot of issues like these.

Given that in all the time d-o-t has been out, we haven't actually had a report about it my guess is the amount of users affected is very low. And given that there is a solution to it that doesn't require forking (= subclasses), I *think* it's okay to reject this. Happy to take more counter-arguments, I could still be convinced.

**Comment by jleclanche** [comment]
(Also happy to document this behaviour and the solution if anyone wants to file a doc PR)

**Comment by JonasSteur** [comment]
Well, the way I did it everything should be backwards compatible. The only 'downside' would be that from now on everyone would get a bit smaller fields. There only would be a real problem if they actually used tokens bigger than 191 characters as those would get truncated. I seriously wonder if that case actually exists considering how ridiculously large those tokens would have to be...

We have some public libraries of our own that we modified like this without any problems. Any new migrations after this point wouldn't be any more complex, they would just continue from the squashed one.

**Comment by jleclanche** [comment]
If we actually want to merge this I think I would rather make it a backwards-incompatible change, single-migration path and advise users who have tokens longer than 191 characters to implement the subclassing method.

**Comment by JonasSteur** [comment]
That's possible indeed. Although I don't think doing it this way would be that problematic. It's the recommended way to handle these situations.

I wouldn't mind doing a PR with a single migration path though, it's a matter of deleting all the old ones and generate a fresh one. Would be most simple and clear for sure.

**Comment by jleclanche** [comment]
No need to delete the old migrations, I just meant a PR that changes the field size from 255 to 191. That migration will loudly fail if you have longer tokens and it can't proceed, thus if you hit that you can subclass your stuff.

Now that I say it out loud that actually doesn't sound too bad to do actually.

**Comment by JonasSteur** [comment]
The problem is that if you do it like this you won't be able to run the old migrations as they will loudly fail as soon as they try to set an indexed field to 255 length. That's how I stumbled upon this issue after all. So the only 2 options are doing it like this or delete and generate new migrations. Other way won't work unfortunately.

**Comment by jleclanche** [comment]
Crap, you're right. Urgh.

**Comment by orf** [comment]
In Mysql is there a way to specify the character collation on a single
column? Is there a need for utfmb8 on this column?

**Comment by JonasSteur** [comment]
It's indeed possible to specify character collation on a single table or column in mysql. To make it work for a user running a mysql utf8mb4 db it would still mean changing the currently existing migrations: Creating the table -> altering it so it's not utf8mb4 by default anymore -> and only then adding the 255 char indexes. Not an improvement over the other 2 solutions imo...

**Pull request closed without merging**
