### PR TITLE
Copy-edit

### PR DESCRIPTION
**Pull request by slashme**
Minor grammar and style edits.

### CODE REVIEW

**Comment by stringsonfire** [comment]
Small misspelling on line 85, `beofre`

**Comment by slashme** [comment]
D'oh! Muphry's law in action :-]

**Comment by slashme** [comment]
Let me know whether you want me to redo the pull request on the current version, so that this will pass the tests, or whether you'll just apply the patch and ignore the failed check.

**Comment by slashme** [comment]
Will redo on fresh code...

**Comment by slashme** [comment]
OK, I've just checked, and nothing has actually changed on the master branch since I did these copy-edits, so the test that fails has nothing to do with this patch, and there is no new code to merge before applying this patch: reopening pull request.

**Comment by poswald** [comment]
I had also done some documentation edits on [this branch](https://github.com/evonove/django-oauth-toolkit/pull/379) but if they collide I'm more than willing to update them there. I would love anyone to look that PR over.

**Pull request merged**
